###Import NumPy as np

In [4]:
import numpy as np

In [5]:
#### Create an array of 10 zeros 

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
#### Create an array of 10 ones

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
#### Create an array of 10 ones fives

In [10]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [12]:
np.zeros(10)+5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [13]:
#### Create an array of the integers from 10 to 50

In [14]:
arr=np.arange

In [15]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [16]:
##Create an array of all the even integers from 10 to 50

In [19]:
even_numbers=[num for num in range(10,51)if num % 2 ==0]

In [20]:
print(even_numbers)

[10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]


In [21]:
##Create a 3x3 matrix with values ranging from 0 to 8

In [32]:
my_list=(0,1,2,3,4,5,6,7,8)
my_list

(0, 1, 2, 3, 4, 5, 6, 7, 8)

In [33]:
my_list

(0, 1, 2, 3, 4, 5, 6, 7, 8)

In [34]:
np.array(my_list)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
my_matrix=[[0,1,2,],[3,4,5,],[6,7,8]]
my_matrix

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

In [37]:
np.array(my_matrix)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [38]:
###Create a 3x3 identity matrix

In [39]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
###Use NumPy to generate a random number between 0 and 1

In [44]:
np.random.rand(1)

array([0.35201634])

In [45]:
###Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution


In [46]:
np.random.randn(25)

array([ 1.4131876 ,  0.2147934 , -0.90773116,  1.191019  ,  0.04673072,
       -1.78902246,  1.13779672,  1.07548365,  1.15489257, -1.82199951,
        0.67401649,  0.1498882 , -0.40536195,  0.34314767, -1.92792737,
        0.82342642,  1.24536946, -0.27545782,  1.11756944,  1.07502703,
        0.49685636, -1.00622497,  0.36013845,  0.2548341 ,  0.16530586])

In [49]:
####Create the following matrix: anuswer  

In [57]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [51]:
##Create an array of 20 linearly spaced points between 0 and 1:

In [53]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

Numpy Indexing and Selection
Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [54]:
arr=np.arange(1,26).reshape(5,5)

In [55]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [58]:
arr2d=arr.reshape(5,5)

In [60]:
arr2d[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [74]:
arr[3][4]

20

In [75]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE


In [76]:
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [78]:
arr2d[0:3,1]

array([ 2,  7, 12])